# Generated by Django 4.2.11 on 2024-04-14 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='year',
            field=models.IntegerField(default=2024, validators=[django.core.validators.MinValueValidator(2015), django.core.validators.MaxValueValidator(2023)]),
        ),
    ]
